### ISSUE TITLE
Make build system simpler

### ISSUE THREAD

**Issue by conradev** [comex/imaon2#3]
I would love to be able to clone the project, run `cargo build` and have it Just Work™. This means things like:
- Making `cargo` the primary build system
- Moving to Rust stable (and replacing use of unstable features with stable code)
- Keeping the generated bindings in source control

I'm not sure if these are things you would consider merging, but I'd love to perhaps spend time working on this.

Farther down the line, it would be super cool to be able to break out some of the Mach-O parsing code into separate crates.

**Comment by comex** [comment]
It would be nice.  The reasons this project doesn't currently use cargo are:
- It uses a _ton_ of small crates as a poor imitation of incremental compilation.  Cargo is obviously not designed for this - it expects each crate to have its own full Cargo.toml and directory structure.  This could be worked around with a stupid script or something, but once rustc gains real incremental compilation this scheme will hopefully become mostly useless and I can bring it down to a handful of crates, so maybe I should just wait for that.
- Bindgen, which I'm using as a binary rather than through the compiler plugin interface since recompiling it every time is really _really_ slow, and compiler plugins aren't stable anyway.  I guess now that `cargo install` is a thing I can just expect it in PATH.  And/or check it in as you say.  By the way, bindgen used to require nightly Rust even for the binary version, but I see it compiles on stable Rust as of a few weeks ago.
- LLVM - though that dependency is broken anyway, and not required for yasce.  Cargo is not great at dealing with native dependencies, so there will probably always be an external build system for the other things I want to do with this project, but yasce could be a pure Cargo build.

Regarding stability - yeah, this code dates back to before Rust 1.0, and used to have significantly more `#![feature` blocks.  Looking at what's left, it mostly consists of `libc` (i.e. the built-in libc crate, which is deprecated in favor of the one in Cargo) and some minor things that could be removed.

**Comment by conradev** [comment]
I see, all of that makes sense!
- I'm interested to see what the compile time is for debug builds if we used modules in one crate versus every module as its own crate, because it may have improved since when this was first built. There might even be specific code that trips up the compiler. (of course, I'm also interested in when incremental compilation will land in nightly)
- I wasn't aware that `bindgen` was originally nightly only! One thing that might be interesting is trying to get the stuff you use to modify the output (in `bindgen.py`) into upstream `bindgen` if it's generic enough.
- Support for native dependencies is certainly not great, but it could be [workable](https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build.rs) (not sure how complex LLVM is as a dependency)

But cool! If I find time to spend on any of this, I'll shoot over a PR.

**Comment by conradev** [comment]
Closing because this is done! 🎉 

also, now that [`CARGO_INCREMENTAL`](https://github.com/rust-lang/cargo/pull/3527) is a thing on nightly, I wonder what build performance would be like now.
